apiVersion: 1

datasources:
  - name: MongoDB
    type: mongodb-datasource
    access: proxy
    orgId: 1
    version: 1
    editable: true
    jsonData:
      connection_string: ${MONGODB_URI}
      db_name: weather_dashboard